# Generated by Django 6.0 on 2025-12-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BORROW', 'Borrow'), ('RETURN', 'Return'), ('MAINTENANCE_IN', 'Maintenance In'), ('MAINTENANCE_OUT', 'Maintenance Out')], max_length=20, verbose_name='Action')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20, verbose_name='Status')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
