# Generated by Django 6.0 on 2026-01-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('BORROW', 'Borrow'), ('RETURN', 'Return'), ('MAINTENANCE_IN', 'Maintenance In'), ('MAINTENANCE_OUT', 'Maintenance Out'), ('MOVE_START', 'Move Start'), ('MOVE_CONFIRM', 'Move Confirm')], max_length=20, verbose_name='Action'),
        ),
    ]
