# Generated by Django 6.0 on 2026-01-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('transactions', '0004_alter_transaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cabinet',
            field=models.CharField(blank=True, max_length=50, verbose_name='櫃'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='號'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='區'),
        ),
    ]
