# Generated by Django 6.0 on 2026-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_cabinet_transaction_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('BORROW', 'Borrow'), ('RETURN', 'Return'), ('MAINTENANCE_IN', 'Maintenance In'), ('MAINTENANCE_OUT', 'Maintenance Out'), ('MOVE_START', 'Move Start'), ('MOVE_CONFIRM', 'Move Confirm'), ('DISPATCH', 'Dispatch')], max_length=20, verbose_name='Action'),
        ),
    ]
