# Generated by Django 6.0 on 2026-01-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin Note'),
        ),
    ]
