# Generated by Django 6.0 on 2025-12-14 14:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '設備', 'verbose_name_plural': '設備列表'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('PERIPHERALS', 'Peripherals'), ('AUDIO_VIDEO', 'Audio/Video'), ('FURNITURE', 'Furniture'), ('DEV_BOARD', 'Development Board'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='設備名稱'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rdf_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='RDF元數據'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('PENDING_RETURN', 'Pending Return'), ('MAINTENANCE', 'Maintenance'), ('LOST', 'Lost'), ('DISPOSED', 'Disposed')], default='AVAILABLE', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='設備UUID'),
        ),
    ]
