# Generated by Django 6.0 on 2025-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_equipment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('PERIPHERALS', 'Peripherals'), ('AUDIO_VIDEO', 'Audio/Video'), ('FURNITURE', 'Furniture'), ('DEV_BOARD', 'Development Board'), ('TABLET', 'Tablet'), ('PHONE', 'Phone'), ('NETWORK', 'Network Equipment'), ('TOOLS', 'Tools'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='類別'),
        ),
    ]
