# Generated by Django 6.0 on 2026-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cabinet',
            field=models.CharField(blank=True, max_length=50, verbose_name='櫃'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='設備圖片'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='號'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='區'),
        ),
    ]
