# Generated by Django 6.0 on 2026-01-08 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipment_status'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_equipment', to='locations.location', verbose_name='目標位置'),
        ),
    ]
