# Generated by Django 6.0 on 2026-01-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipment_target_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='target_cabinet',
            field=models.CharField(blank=True, max_length=50, verbose_name='目標櫃'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='target_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='目標號'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='target_zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='目標區'),
        ),
    ]
