# Generated by Django 6.0 on 2026-01-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipment_target_cabinet_equipment_target_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '設備類別',
                'verbose_name_plural': '設備類別列表',
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
    ]
