# Generated by Django 6.0 on 2026-01-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_category_remove_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='equipment.category', verbose_name='類別'),
        ),
    ]
