# Generated by Django 6.0 on 2026-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('PENDING_BORROW', 'Pending Borrow'), ('PENDING_RETURN', 'Pending Return'), ('MAINTENANCE', 'Maintenance'), ('TO_BE_MOVED', 'To Be Moved'), ('IN_TRANSIT', 'In Transit'), ('LOST', 'Lost'), ('DISPATCHED', 'Dispatched'), ('DISPOSED', 'Disposed')], default='AVAILABLE', max_length=20, verbose_name='狀態'),
        ),
    ]
