/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["v1_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_categories_list"];
        put?: never;
        post: operations["v1_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_categories_retrieve"];
        put: operations["v1_categories_update"];
        post?: never;
        delete: operations["v1_categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_categories_partial_update"];
        trace?: never;
    };
    "/api/v1/equipment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_equipment_list"];
        put?: never;
        post: operations["v1_equipment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_equipment_retrieve"];
        put: operations["v1_equipment_update"];
        post?: never;
        delete: operations["v1_equipment_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_equipment_partial_update"];
        trace?: never;
    };
    "/api/v1/equipment/{uuid}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_equipment_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/{uuid}/qr/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_equipment_qr_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipment/bulk-delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_equipment_bulk_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_locations_list"];
        put?: never;
        post: operations["v1_locations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_locations_retrieve"];
        put: operations["v1_locations_update"];
        post?: never;
        delete: operations["v1_locations_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_locations_partial_update"];
        trace?: never;
    };
    "/api/v1/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_transactions_list"];
        put?: never;
        post: operations["v1_transactions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_transactions_retrieve"];
        put: operations["v1_transactions_update"];
        post?: never;
        delete: operations["v1_transactions_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_transactions_partial_update"];
        trace?: never;
    };
    "/api/v1/transactions/{id}/approve-borrow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_approve_borrow_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/approve-dispatch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_approve_dispatch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/approve-return/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_approve_return_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/reject-borrow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_reject_borrow_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/reject-dispatch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_reject_dispatch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/reject-return/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_reject_return_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/borrow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_borrow_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/bulk-approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approve multiple transactions at once */
        post: operations["v1_transactions_bulk_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/dispatch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Request equipment to be dispatched (outbound) */
        post: operations["v1_transactions_dispatch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/return-request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_transactions_return_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_users_list"];
        put?: never;
        post: operations["v1_users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_users_retrieve"];
        put: operations["v1_users_update"];
        post?: never;
        delete: operations["v1_users_destroy"];
        options?: never;
        head?: never;
        patch: operations["v1_users_partial_update"];
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `BORROW` - Borrow
         *     * `RETURN` - Return
         *     * `MAINTENANCE_IN` - Maintenance In
         *     * `MAINTENANCE_OUT` - Maintenance Out
         *     * `MOVE_START` - Move Start
         *     * `MOVE_CONFIRM` - Move Confirm
         *     * `DISPATCH` - Dispatch
         * @enum {string}
         */
        ActionEnum: "BORROW" | "RETURN" | "MAINTENANCE_IN" | "MAINTENANCE_OUT" | "MOVE_START" | "MOVE_CONFIRM" | "DISPATCH";
        Attachment: {
            readonly id: number;
            /**
             * 檔案
             * Format: uri
             */
            file: string;
            /** Format: date-time */
            readonly uploaded_at: string;
        };
        Category: {
            readonly id: number;
            /** 類別名稱 */
            name: string;
            /** 描述 */
            description?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        Equipment: {
            /**
             * 設備UUID
             * Format: uuid
             */
            readonly uuid: string;
            /** 設備名稱 */
            name: string;
            /** 描述 */
            description?: string;
            /** 狀態 */
            status?: components["schemas"]["EquipmentStatusEnum"];
            category?: number | null;
            readonly category_details: components["schemas"]["Category"];
            /**
             * Location UUID
             * Format: uuid
             */
            location?: string | null;
            readonly location_details: components["schemas"]["Location"];
            /**
             * 目標位置
             * Format: uuid
             */
            target_location?: string | null;
            readonly target_location_details: components["schemas"]["Location"];
            /** 區 */
            zone?: string;
            /** 櫃 */
            cabinet?: string;
            /** 號 */
            number?: string;
            /** 目標區 */
            target_zone?: string;
            /** 目標櫃 */
            target_cabinet?: string;
            /** 目標號 */
            target_number?: string;
            /** Format: uri */
            image?: string | null;
            /** RDF元數據 */
            rdf_metadata?: unknown;
            /**
             * 建立時間
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * 更新時間
             * Format: date-time
             */
            readonly updated_at: string;
            readonly attachments: components["schemas"]["Attachment"][];
            readonly current_possession: string;
        };
        /**
         * @description * `AVAILABLE` - Available
         *     * `BORROWED` - Borrowed
         *     * `PENDING_BORROW` - Pending Borrow
         *     * `PENDING_RETURN` - Pending Return
         *     * `PENDING_DISPATCH` - Pending Dispatch
         *     * `MAINTENANCE` - Maintenance
         *     * `TO_BE_MOVED` - To Be Moved
         *     * `IN_TRANSIT` - In Transit
         *     * `LOST` - Lost
         *     * `DISPATCHED` - Dispatched
         *     * `DISPOSED` - Disposed
         * @enum {string}
         */
        EquipmentStatusEnum: "AVAILABLE" | "BORROWED" | "PENDING_BORROW" | "PENDING_RETURN" | "PENDING_DISPATCH" | "MAINTENANCE" | "TO_BE_MOVED" | "IN_TRANSIT" | "LOST" | "DISPATCHED" | "DISPOSED";
        Location: {
            /**
             * Location UUID
             * Format: uuid
             */
            readonly uuid: string;
            /** Location Name */
            name: string;
            description?: string;
            /**
             * Parent Location
             * Format: uuid
             */
            parent?: string | null;
            readonly full_path: string;
            readonly children: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedEquipmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Equipment"][];
        };
        PaginatedTransactionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Transaction"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        PatchedCategory: {
            readonly id?: number;
            /** 類別名稱 */
            name?: string;
            /** 描述 */
            description?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedEquipment: {
            /**
             * 設備UUID
             * Format: uuid
             */
            readonly uuid?: string;
            /** 設備名稱 */
            name?: string;
            /** 描述 */
            description?: string;
            /** 狀態 */
            status?: components["schemas"]["EquipmentStatusEnum"];
            category?: number | null;
            readonly category_details?: components["schemas"]["Category"];
            /**
             * Location UUID
             * Format: uuid
             */
            location?: string | null;
            readonly location_details?: components["schemas"]["Location"];
            /**
             * 目標位置
             * Format: uuid
             */
            target_location?: string | null;
            readonly target_location_details?: components["schemas"]["Location"];
            /** 區 */
            zone?: string;
            /** 櫃 */
            cabinet?: string;
            /** 號 */
            number?: string;
            /** 目標區 */
            target_zone?: string;
            /** 目標櫃 */
            target_cabinet?: string;
            /** 目標號 */
            target_number?: string;
            /** Format: uri */
            image?: string | null;
            /** RDF元數據 */
            rdf_metadata?: unknown;
            /**
             * 建立時間
             * Format: date-time
             */
            readonly created_at?: string;
            /**
             * 更新時間
             * Format: date-time
             */
            readonly updated_at?: string;
            readonly attachments?: components["schemas"]["Attachment"][];
            readonly current_possession?: string;
        };
        PatchedLocation: {
            /**
             * Location UUID
             * Format: uuid
             */
            readonly uuid?: string;
            /** Location Name */
            name?: string;
            description?: string;
            /**
             * Parent Location
             * Format: uuid
             */
            parent?: string | null;
            readonly full_path?: string;
            readonly children?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedTransaction: {
            readonly id?: number;
            /** 動作 */
            action?: components["schemas"]["ActionEnum"];
            readonly status?: components["schemas"]["TransactionStatusEnum"];
            /** Format: date-time */
            due_date?: string | null;
            reason?: string;
            admin_note?: string;
            readonly image?: string;
            /**
             * 設備UUID
             * Format: uuid
             */
            equipment?: string;
            /** Requester */
            readonly user?: number;
            readonly admin_verifier?: number | null;
            /**
             * Location UUID
             * Format: uuid
             */
            location?: string | null;
            readonly location_details?: components["schemas"]["Location"];
            /** 區 */
            zone?: string;
            /** 櫃 */
            cabinet?: string;
            /** 號 */
            number?: string;
            readonly user_detail?: components["schemas"]["User"];
            readonly equipment_detail?: components["schemas"]["Equipment"];
            readonly admin_verifier_detail?: components["schemas"]["User"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedUser: {
            readonly id?: number;
            /**
             * 使用者名稱
             * @description 必填。長度為150個字或以下，僅限字母、數字和 @/./+/-/_。
             */
            username?: string;
            /**
             * 電子郵件
             * Format: email
             */
            email?: string | null;
            /** 角色 */
            role?: components["schemas"]["RoleEnum"];
            /**
             * 頭像URL
             * Format: uri
             */
            avatar_url?: string | null;
            /** 名字 */
            first_name?: string;
            /** 姓氏 */
            last_name?: string;
        };
        /**
         * @description * `ADMIN` - Admin
         *     * `MANAGER` - Manager
         *     * `USER` - User
         * @enum {string}
         */
        RoleEnum: "ADMIN" | "MANAGER" | "USER";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        Transaction: {
            readonly id: number;
            /** 動作 */
            action: components["schemas"]["ActionEnum"];
            readonly status: components["schemas"]["TransactionStatusEnum"];
            /** Format: date-time */
            due_date?: string | null;
            reason?: string;
            admin_note?: string;
            readonly image: string;
            /**
             * 設備UUID
             * Format: uuid
             */
            equipment: string;
            /** Requester */
            readonly user: number;
            readonly admin_verifier: number | null;
            /**
             * Location UUID
             * Format: uuid
             */
            location?: string | null;
            readonly location_details: components["schemas"]["Location"];
            /** 區 */
            zone?: string;
            /** 櫃 */
            cabinet?: string;
            /** 號 */
            number?: string;
            readonly user_detail: components["schemas"]["User"];
            readonly equipment_detail: components["schemas"]["Equipment"];
            readonly admin_verifier_detail: components["schemas"]["User"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `COMPLETED` - Completed
         *     * `PENDING_APPROVAL` - Pending Approval
         *     * `REJECTED` - Rejected
         * @enum {string}
         */
        TransactionStatusEnum: "COMPLETED" | "PENDING_APPROVAL" | "REJECTED";
        User: {
            readonly id: number;
            /**
             * 使用者名稱
             * @description 必填。長度為150個字或以下，僅限字母、數字和 @/./+/-/_。
             */
            username: string;
            /**
             * 電子郵件
             * Format: email
             */
            email?: string | null;
            /** 角色 */
            role?: components["schemas"]["RoleEnum"];
            /**
             * 頭像URL
             * Format: uri
             */
            avatar_url?: string | null;
            /** 名字 */
            first_name?: string;
            /** 姓氏 */
            last_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    v1_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    v1_categories_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    v1_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    v1_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 設備類別. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    v1_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 設備類別. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    v1_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 設備類別. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 設備類別. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
                "multipart/form-data": components["schemas"]["PatchedCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    v1_equipment_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEquipmentList"];
                };
            };
        };
    };
    v1_equipment_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Equipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Equipment"];
                "multipart/form-data": components["schemas"]["Equipment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    v1_equipment_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this 設備. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    v1_equipment_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this 設備. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Equipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Equipment"];
                "multipart/form-data": components["schemas"]["Equipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    v1_equipment_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this 設備. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_equipment_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this 設備. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEquipment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEquipment"];
                "multipart/form-data": components["schemas"]["PatchedEquipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    v1_equipment_history_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this 設備. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    v1_equipment_qr_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this 設備. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    v1_equipment_bulk_delete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Equipment"];
                "application/x-www-form-urlencoded": components["schemas"]["Equipment"];
                "multipart/form-data": components["schemas"]["Equipment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment"];
                };
            };
        };
    };
    v1_locations_list: {
        parameters: {
            query?: {
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
        };
    };
    v1_locations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Location"];
                "application/x-www-form-urlencoded": components["schemas"]["Location"];
                "multipart/form-data": components["schemas"]["Location"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    v1_locations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Location. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    v1_locations_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Location. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Location"];
                "application/x-www-form-urlencoded": components["schemas"]["Location"];
                "multipart/form-data": components["schemas"]["Location"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    v1_locations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Location. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_locations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this Location. */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLocation"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLocation"];
                "multipart/form-data": components["schemas"]["PatchedLocation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    v1_transactions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTransactionList"];
                };
            };
        };
    };
    v1_transactions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_transactions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTransaction"];
                "multipart/form-data": components["schemas"]["PatchedTransaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_approve_borrow_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_approve_dispatch_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_approve_return_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_reject_borrow_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_reject_dispatch_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_reject_return_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this transaction. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_borrow_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_bulk_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_dispatch_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_transactions_return_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transaction"];
                "application/x-www-form-urlencoded": components["schemas"]["Transaction"];
                "multipart/form-data": components["schemas"]["Transaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    v1_users_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    v1_users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 使用者. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 使用者. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 使用者. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this 使用者. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
